dt-bindings: net: adin: Escape a trailing ":"
1f77204e11f8 ("dt-bindings: net: adin: document phy clock output
properties") added a line with a ":" at the end, which is tripping up my
attempts to run the DT schema checks due to this being invalid YAML
syntax.  I get a schema check failure with the following error

    ruamel.yaml.scanner.ScannerError: mapping values are not allowed in this context

This just escapes the line in question, so it can parse.

Fixes: 1f77204e11f8 ("dt-bindings: net: adin: document phy clock output properties")
Signed-off-by: Palmer Dabbelt <palmer@rivosinc.com>